version: '3.8'

services:
  markdown-to-pdf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markdown_to_pdf_converter
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: unless-stopped
