version: '3.8'

services:
  markdown-to-pdf:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: markdown_to_pdf_converter
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DEFAULT_PAGE_SIZE=A4
      - DEFAULT_ORIENTATION=portrait
      - DEFAULT_MARGIN_TOP=20mm
      - DEFAULT_MARGIN_BOTTOM=20mm
      - DEFAULT_MARGIN_LEFT=20mm
      - DEFAULT_MARGIN_RIGHT=20mm
    restart: unless-stopped
